module.exports.recipes = [
    {title: "HONEY PORK WITH BOK CHOY",
    rating: 5,
    category: "Dinner",
    image: "public/images/meals/honey_pork_with_bok_choy.png",
    servings: 2,
    time: {
        prep: 15,
        cook: 40,
    },
    ingredientList: [{ section: [{ title: "Main",
                            ingredients: [{  ingredient: "Brown rice (rinsed)", quantity: "1", unit: "cup"},
                                            {ingredient: "Water", quantity: "2", unit: "cups"},
                                            {ingredient: "Salt", quantity: "0.75", unit: "tsp"},
                                            {ingredient: "Sesame seeds", quantity: "2", unit: "tsp"},
                                            {ingredient: "Coconut oil", quantity: "4", unit: "tsp"},
                                            {ingredient: "Scallions thinly sliced, plus extra to serve", quantity: "2", unit: ""},
                                            {ingredient: "Fresh ginger finely grated", quantity: "2", unit: "tsp"},
                                            {ingredient: "Bunch of babby bok choy (halved lengthways)", quantity: "1", unit: "bunch"},
                                            {ingredient: "Pork fillet thinly sliced", quantity: "18", unit: "oz"}]},
                                { title: "Sauce",
                            ingredients: [{  ingredient: "Cornstarch", quantity: "1.5", unit: "tsp"},
                                            {ingredient: "Soy sauce (or tamari if gluten free)", quantity: "3", unit: "tsp"},
                                            {ingredient: "Shaoxing (Chinese cooking wine)", quantity: "1.5", unit: "tbs"},
                                            {ingredient: "Honey (brown rice syrup or maple syrup", quantity: "3", unit: "tsp"},
                                            {ingredient: "Water", quantity: "1.5", unit: "tbs"}]}
                                ]}],
    method: [   "Place rice, water and salt in a small saucepan and bring to the boil. Reduce to a simmer, cover and cook for 30 minutes. Remove from heat and stand for 5 minutes before fluffing with a fork.",
                "Meanwhile, to make the sauce, mix corn starch and soy together in a small bowl until smooth. Add Shaoxing, honey and water and mix to combine. Set aside.",
                "Heat sesame seeds in a dry wok or non-stick skillet over medium heat and toss for 1 minute until golden brown. Transfer to a bowl and set aside to cool.",
                "Add half the oil, scallions, ginger and bok choy to the hot wok and stir fry for 4-5 minutes until bok choy is crisp-tender. Transfer to a plate.",
                "Add remaining oil and pork to wok and stir fry for 3-4 minutes until just cooked. Add sauce and bok choy to the pork and toss for a minute to warm through and thicken sauce.",
                "Divide rice and pork between bowls and top with extra scallions and sesame seeds to serve."]
    },
    
    {title: "BALI BUDDHA BOWL",
    rating: 5,
    category: "Dinner",
    image: "public/images/meals/bali_buddha_bowl.png",
    servings: 2,
    time: {
        prep: 15,
        cook: 0,
    },
    ingredientList: [{ section: [{ title: "Main",
                            ingredients: [{  ingredient: "Kale leaves stripped & chopped", quantity: 0.25, unit: "bunch"},
                                            {ingredient: "Brown & wild rice, pre-cooked blend cooked according to packet directions", quantity: 1.5, unit: "cups"},
                                            {ingredient: "Medium carrot spiralized", quantity: 1, unit: ""},
                                            {ingredient: "Avocado diced", quantity: 0.25, unit: ""},
                                            {ingredient: "Chickpeas (14 oz can) drained & rinsed", quantity: 1, unit: "can"},
                                            {ingredient: "Pepitas toasted, optional", quantity: 3, unit: "tbs"}]},
                                { title: "Sauce",
                            ingredients: [{  ingredient: "Soy sauce (or tamari if gluten free) or coconut aminos", quantity: 3, unit: "tbs"},
                                            {ingredient: "Lime juice", quantity: 2, unit: "tbs"},
                                            {ingredient: "Maple syrup (honey or rice malt syrup)", quantity: 2, unit: "tsp"},
                                            {ingredient: "Crunchy natural peanut butter", quantity: 1.5, unit: "tsp"},
                                            {ingredient: "Sriracha sauce (chilli garlic sauce)", quantity: 2, unit: "tsp"}]}
                                ]}],
    method: [   "Place kale in a medium bowl, submerge in boiling water and cover with a saucer or cling film. Drain after 5 minutes and pat dry.",
                "Meanwhile, to make satay sauce, whisk all ingredients in a bowl. Adjust seasoning, adding a little more soy if too thick and set aside.",
                "Add rice to serving bowls and top with kale, carrot, avocado, chickpeas and pepitas.",
                "Drizzle over satay sauce to serve."]
    },

    {title: "BBQ LAMB & MIXED PEPPER SALAD",
    rating: 5,
    category: "Dinner",
    image: "public/images/meals/bbq_lamb_mixed_pepper_salad.png",
    servings: 2,
    time: {
        prep: 10,
        cook: 15,
    },
    ingredientList: [{ section: [{ title: "Main",
                            ingredients: [{  ingredient: "White quinoa rinsed", quantity: 1.25, unit: "cups"},
                                            {ingredient: "Water", quantity: 2.5, unit: "cups"},
                                            {ingredient: "Salt", quantity: 1, unit: "tsp"},
                                            {ingredient: "Red bell pepper deseeded & sliced", quantity: 1, unit: ""},
                                            {ingredient: "Yellow bell pepper (deseeded & sliced)", quantity: 1, unit: ""},
                                            {ingredient: "Baby spinach leaves", quantity: 2, unit: "oz"},
                                            {ingredient: "Lemon half juiced & half cut into wedges", quantity: 1, unit: ""},
                                            {ingredient: "Feta crumbled", quantity: 1, unit: "oz"}]}
                                ]}],
    method: [   "Place quinoa, water and salt in a saucepan and bring to the boil. Lower heat and simmer, covered for 12 minutes or until just cooked. Rest covered for 5 minutes then fluff with a fork.",
                "Meanwhile, preheat a BBQ or non-stick griddle pan over medium-high heat. Season lamb with salt and pepper and cook for 3-4 minutes each side for medium, or until cooked to your liking. Transfer to a plate, cover loosely and rest for 5-10 minutes before slicing.",
                "Add bell peppers to BBQ and cook for 5-8 minutes, tossing occasionally, until tender.",
                "Toss quinoa with spinach and lemon juice and adjust seasoning.",
                "Divide quinoa and bell pepper slices between plates and top with lamb, feta and lemon wedge to serve."]
    },

    {title: "KOREAN BEEF BULGOGI BOWL",
    rating: 5,
    category: "Dinner",
    image: "public/images/meals/korean_beef_bulgogi_bowl.png",
    servings: 2,
    time: {
        prep: 10,
        cook: 30,
    },
    ingredientList: [{ section: [{ title: "Main",
                            ingredients: [{  ingredient: "Brown rice rinsed", quantity: 0.75, unit: "cup"},
                                            {ingredient: "Water", quantity: 1.5, unit: "cups"},
                                            {ingredient: "Salt", quantity: 0.25, unit: "tsp"},
                                            {ingredient: "Onion grated", quantity: 0.5, unit: ""},
                                            {ingredient: "Garlic clove minced", quantity: 1, unit: ""},
                                            {ingredient: "Fresh ginger finely grated", quantity: 1, unit: "tsp"},
                                            {ingredient: "Soy sauce (or tamari if gluten free)", quantity: 1, unit: "tbs"},
                                            {ingredient: "Honey (brown rice syrup or maple syrup)", quantity: 1, unit: "tsp"},
                                            {ingredient: "Sesame oil", quantity: 2, unit: "tsp"},
                                            {ingredient: "Beef steak thinly sliced", quantity: 14, unit: "oz"},
                                            {ingredient: "Broccoli cut in small florets", quantity: 4, unit: "oz"},
                                            {ingredient: "Frozen podded edamame defrosted", quantity: 2, unit: "oz"},
                                            {ingredient: "Kimchi", quantity: 2.5, unit: "oz"},
                                            {ingredient: "Scallions thinly sliced diagonally", quantity: 2, unit: ""},
                                            {ingredient: "Unsalted peanuts chopped", quantity: 0.5, unit: "oz"}]}
                                ]}],
    method: [   "Place rice, water and salt in a saucepan and simmer, covered for 30 minutes. Remove from heat and stand for 5 minutes before fluffing with a fork.",
                "At the same time, place onion, garlic, ginger, soy, honey and half the sesame oil in a bowl and whisk to combine. Add beef and toss to coat. Cover and marinate in the refrigerator for 25 minutes.",
                "In last 5 minutes of rice cooking, heat a wok or large non-stick skillet over high heat. Drain beef from marinade, reserving the marinade.",
                "Add remaining sesame oil to the hot wok and stir-fry half the beef for 1-2 minutes or until just cooked, set aside. Cook remaining beef and set aside with other cooked beef.",
                "Toss broccoli in remaining marinade, adding a little water if needed, and stir-fry for a few minutes until crisp-tender, adding edamame for last minute to heat through.",
                "Divide rice between bowls and top with beef, vegetables and kimchi. Scatter over scallions and peanuts to serve."]
    },

    {title: "BAKED SALMON WITH SWEET POTATO SALAD",
    rating: 5,
    category: "Dinner",
    image: "public/images/meals/baked_salmon_with_sweet_potato_salad.png",
    servings: 2,
    time: {
        prep: 15,
        cook: 25,
    },
    ingredientList: [{ section: [{ title: "Main",
                            ingredients: [{  ingredient: "Sweet potatoes peeled & sliced diagonally", quantity: 28, unit: "oz"},
                                            {ingredient: "Olive oil", quantity: 1, unit: "tsp"},
                                            {ingredient: "Pine nuts", quantity: 2, unit: "tsp"},
                                            {ingredient: "Dried oregano", quantity: 0.5, unit: "tsp"},
                                            {ingredient: "Salmon fillets", quantity: 16, unit: "oz"},
                                            {ingredient: "Cherry tomatoes halved", quantity: 3.5, unit: "oz"},
                                            {ingredient: "Baby spinach leaves", quantity: 1, unit: "cup"},
                                            {ingredient: "Lemon", quantity: 0.5, unit: ""}]}
                                ]}],
    method: [   "Preheat oven to 355°F and line a baking sheet with baking paper.",
                "Toss sweet potato with oil and arrange on sheet. Season with salt and pepper and roast for 15 minutes.",
                "At the same time, roast pine nuts for 3-4 minutes until golden and set aside.",
                "Rub oregano over salmon and add to the sheet of sweet potato. Add tomatoes and return the sheet to oven for a further 10 minutes or until potato is tender and salmon is just cooked.",
                "Divide spinach between plates and top with sweet potato, tomatoes and pine nuts. Add salmon, season and squeeze over lemon to serve."]
    },

    {title: "ONE POT CHICKEN MEATBALLS WITH RISONI",
    rating: 5,
    category: "Dinner",
    image: "public/images/meals/one_pot_chicken_meatballs_with_risoni.png",
    servings: 2,
    time: {
        prep: 15,
        cook: 15,
    },
    ingredientList: [{ section: [{ title: "Main",
                            ingredients: [{  ingredient: "Ground chicken", quantity: 14, unit: "oz"},
                                            {ingredient: "Parmesan finely grated", quantity: 3, unit: "tbs"},
                                            {ingredient: "Zucchini finely grated & excess water squeezed out", quantity: 1, unit: ""},
                                            {ingredient: "Garlic clove minced", quantity: 1, unit: ""},
                                            {ingredient: "Fresh basil leaves picked & finely chopped, plus extra to serve", quantity: 2, unit: "sprigs"},
                                            {ingredient: "Tomato sauce or puree", quantity: 24, unit: "oz"},
                                            {ingredient: "Chicken stock", quantity: 2, unit: "cups"},
                                            {ingredient: "Risoni pasta (or gluten free)", quantity: 7, unit: "oz"},
                                            {ingredient: "Mixed salad leaves", quantity: 1.5, unit: "oz"},
                                            {ingredient: "Lemon juiced", quantity: 1, unit: ""}]}
                                ]}],
    method: [   "Combine mince, parmesan, zucchini, garlic and basil in a bowl. Season with salt and pepper and mix well to combine. With wet hands divide mixture into even tablespoon-sized portions and roll meatballs (mixture will be soft but manageable).",
                "Heat a large non-stick skillet over medium heat and cook meatballs for 3-5 minutes, turning until browned all over.",
                "Add tomato puree, stock and risoni to pan with meatballs and stir to combine. Bring to a simmer and cook uncovered for 10 minutes, or until pasta and meatballs are cooked and sauce has thickened.",
                "Meanwhile toss salad leaves with lemon juice and season with salt and pepper.",
                "Divide meatballs and sauce between bowls, top with extra basil and serve with salad."]
    }
]